[package]
name = "packager"
version.workspace = true
edition.workspace = true

[[bin]]
name = "mod-packager"
path = "src/main.rs"

[dependencies]
common = { path = "../common" }
serde.workspace = true
toml.workspace = true
semver.workspace = true
anyhow.workspace = true
clap = { version = "4", features = ["derive"] }
tar = "0.4"
zstd = "0.13"
zip = { version = "2", default-features = false, features = ["deflate"] }
chrono = { version = "0.4", default-features = false, features = ["clock"] }
